// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xvueochemkzeijnuoofw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh2dWVvY2hlbWt6ZWlqbnVvb2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMDYxOTQsImV4cCI6MjA1OTg4MjE5NH0.YX9JPvyWbY9SlrqIvkvm2WeV8-RQxhveXG_CvW_8GmI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);